/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <app_main.h>
#include <service.h>
#include <app_feature.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint16_t adc_value = 0;
float converted_value = 0.0;
volatile uint8_t reset_reason = 0;

/// variables for the time measurements
volatile uint32_t start_time_ms = 0;
volatile uint32_t end_time_ms = 0;
volatile uint32_t loop_time_ms = 0;

void service_init()
{
	/// System timer start
	systick_init();
	/// Setting up the watchdog
	init_independent_watchdog();
	/// Setting up the temperature sensor
	adc_init_common(ADC_INDEPENDENT_MODE);
	adc_init_module(adc1_ptr , 16, INTERNAL_CHANNEL_TEMPERATURE_SENSOR , ALL_CYCLE_CONVERSION , 1);
	adc_start_conversion(adc1_ptr);
	/// Setting up user pin and LED pin
	pin_init(PIN_0,PIN_GENERAL_INPUT,PORTA);
	pin_init(PIN_12,PIN_OUTPUT,PORTD);
}

void app_init()
{
	reset_reason_check(&reset_reason);
}

int main(void)
{
    service_init();
    app_init();

    while (1)
    {
    	start_time_ms = system_timer_1ms;
    	adc_get_value(adc1_ptr,&adc_value);
    	adc_convert_value(adc_value,&converted_value,INNER_TEMPERATURE_SENSOR);

    	/// manual delay in the program
    	blocking_delay_ms(50);

    	end_time_ms = system_timer_1ms;
    	loop_time_ms = end_time_ms - start_time_ms;
    	if (loop_time_ms < MAX_LOOP_TIME_MS)
    	{
    		feed_watchdog();
    	}
    	watchdog_blocking_program();
    }
}
