/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <app_main.h>
#include <service.h>
#include <app_feature.h>
#include "APP_task.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t rx_byte = 0;

void service_init()
{
	/// Step 1 - Enable the clock for GPIOD . we are creating task for blue LED which is in PORT D
	gpio_clock_enable(PORTD);
	/// Step 2 - Set the pin to output
	gpio_pin_set_mode(PORTD_BLUE_LED_PIN , PIN_OUTPUT , gpiod_ptr);
}

void app_init()
{
	;
}

int main(void)
{

	service_init();
    app_task_init();

    while(1)
    {
    	;
    }
}
