/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <app_main.h>
#include <service.h>
#include <app_feature.h>
#include <rtos.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void blink_led2(void *param);
void blink_led1(void *param);

void service_init()
{
	pin_init(BLUE_LED_PIN,PIN_OUTPUT,PORTD);
	pin_init(GREEN_LED_PIN,PIN_OUTPUT,PORTD);
}

void app_init()
{
    // empty for now
}

int main(void)
{
    service_init();
    app_init();

    /// we will create the 1st task here
    xTaskCreate(blink_led1,"Task_1",128,NULL,2,NULL);
    xTaskCreate(blink_led2,"Task_2",128,NULL,2,NULL);
    vTaskStartScheduler();

}


void blink_led1(void *param)
{
    while (1)
    {
    	pin_operations(BLUE_LED_PIN,TOGGLE);
        vTaskDelay(10 / portTICK_PERIOD_MS);
    }
}

void blink_led2(void *param)
{
    while (1)
    {
    	pin_operations(GREEN_LED_PIN,TOGGLE);
        vTaskDelay(10 / portTICK_PERIOD_MS);
    }
}


void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    /* This function will be called if a stack overflow is detected. */

    (void)xTask;
    (void)pcTaskName;

    // Stop here for debugging
    taskDISABLE_INTERRUPTS();
    while(1);
}

