/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <app_main.h>
#include <service.h>
#include <app_feature.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t rx_byte = 0;

void service_init()
{
	/// Step 1 - Enable the clock for GPIOA . we are using port a pins for SPI1
	gpio_clock_enable(PORTA);
	/// Step 2 - Enable clock for SPI1
	spi_clock_enable(SPI1);
	/// Step 3 - Pin init configurations
	gpio_spi1_config();
	/// Step 4 - SPI init configurations
	spi_init_config(spi1_ptr);
}

void app_init()
{

}

int main(void)
{
    service_init();
    app_init();

    while(1)
    {
    	/// This is a loopback test . So connect PA6 to PA7 for testing ( Mosi to Miso )
    	gpio_output_operations(gpioa_ptr,SPI1_NSS,SET_LOW);
        rx_byte = spi_transfer(spi1_ptr, 0xA5);
        rx_byte = spi_transfer(spi1_ptr, 0x60);
        rx_byte = spi_transfer(spi1_ptr, 0x15);
        gpio_output_operations(gpioa_ptr,SPI1_NSS,SET_HIGH);
    }
}
